import {Prisma, PrismaClient} from '../generated/client/deno/edge.ts'
import { load } from "https://deno.land/std/dotenv/mod.ts";

const env = await load();

const prisma = new PrismaClient({
    datasources: {
        db: {
            url: env["DATABASE_URL"]
        }
    }
})

// Uncomment to seed data 
// const newUser = await prisma.user.create({
//     data: {
//         name: 'John', 
//         username: 'Linus',
//         email: 'john@gmail.com'
//     },
// });

// const newMemory = await prisma.memory.create({
//     data: {
//         title: 'I bought a book', 
//         content: 'I bought new book called AI on Business',
//         userId: 3
//     },
// });

// console.log(`User has been created with id: ${newUser.id}`);
// console.log(`User has been created with id: ${newMemory.id}`);
await prisma.$disconnect()


/**  
 * run command to seed: >deno run -A prisma/seed.ts
 * other ways to create rows in prisma, here id not autogenerated
  const newUser = await prisma.user.create({
    data: { id: 4 ,name: 'Bob', email: 'bob@prisma.io' },
});

const newUser = await prisma.user.createMany({
    data: [
      {id: 5,name: 'Peter', email: 'peter@prisma.io' },
      { id: 6,name: 'Jane', email: 'jane@prisma.io' },
    ]
});

 */